### ISSUE TITLE
What dat fock Oo

### ISSUE THREAD

**Issue by LiliumElfenLIED** [enjoy2000/discord-pokemon-go-snipe-bot#81]
Hello everyone,

After the problem this morning which is set, the bot does not work.

py bot.py srawl : 

http://image.prntscr.com/image/cb128da4d4424a9d9ddfda0cb267aa7c.png

py bot.py trackemon : 

http://image.prntscr.com/image/384c84995fa84aebba213d738aa8ed9a.png

Your Home is work?

**Comment by phr34k0** [comment]
Is not the bot. Its both of the trackemon and pokesniper site gets offline pretty much like everytime. Due to thousands people using the pogofeeder that pulls requests from these sites, even with cloudflare (which is 99% of time useless security wise and ddos prevention wise due to cfscrape to fetch data etc) the sites get flooded all the time. Hence, is why pulling info not just from these two but discord channels are better

**Comment by Navyguy330** [comment]
[20:27:43]  Can't retrieve session id for api. Waiting for next scrawl..
[20:27:43] ←[91m Cannot retrieve session id for Trackemon.. Trying again ←[0m

**Comment by itsDustinBerry** [comment]
It is the bot.

Pokesnipers isn't putting as much coords up anymore.
It'll maybe pull 2 - 3 coords then error out

and as for trackemon, the owner posted here and said he is changing things up because he doesn't want the bot pulling coords from his website because with all the 3rd party apps, it is 10x the normal traffic.

**Comment by phr34k0** [comment]
Get a feed. Been telling u people to scrape off pogo-feed.mmoex.com/messages

**Comment by yosang** [comment]
@phr34k0 would you please tell how to configure the bot to do that?

**Comment by phr34k0** [comment]
API is down. Please close this issue
